notifications:
  email:
    on_success: never

sudo: false

language: php

php: 7.1

branches:
  only:
  - master

cache:
  directories:
    - vendor

install:
  - alias composer=composer\ -n && composer selfupdate
  - composer validate
  - composer install --no-progress --no-suggest $DEPENDENCIES

before_script:
  - snapshots=$(vendor/bin/250\ data download-last2 | head -1) && echo "$snapshots"
  - 'echo "db: \"${db=$(cut -f3 <<<"$snapshots")}\""'

script:
  - bin/curator -v sync "$db" 32686107 SteamTop250 -p "$STEAM_PASSWORD" || exit
